### ISSUE TITLE
a bug in LHD

### ISSUE THREAD

**Issue by 1a1a11a** [sunnyszy/lrb#11]
There is a bug in LHD, because size is set after LHD initialization, LHD uses `-1/INT64_MAX` to initialize `explorerBudget`, which effectively becomes infinite.

**Comment by sunnyszy** [comment]
Hi @1a1a11a ,

Thank you for reporting this bug! I did a quick fix in https://github.com/sunnyszy/lrb/commit/fb03d938f405abc0aa14ac6171c9e57b43e19072.

**Comment by 1a1a11a** [comment]
:)
