### ISSUE TITLE
How did you collect the Dataset?

### ISSUE THREAD

**Issue by Keshvadi** [sunnyszy/lrb#14]
Hi, 

Thanks for you interesting work and making code and dataset available.

I just wanted to know where did you get the dataset? Did you collect it?
I appreciate it if you can give me some information.

**Comment by sunnyszy** [comment]
Hi,

The dataset collection is done by @dasebe. You may ask him for more information.

**Comment by Keshvadi** [comment]
> I think we primarily link to the two Wikipedia CDN traces, which are public. We collaborated with the Wikimedia Operators to record these.
> 
> Are you asking for other datasets?
Hi Daniel, 
Thanks. I just wanted to know where was the vantage point that you collected the requests to the Wikipedia.
I got my answer (Wikimedia Operators). Thanks.

**Comment by Keshvadi** [comment]
Hi Daniel @dasebe 
Thanks. I just wanted to know where was the vantage point that you collected the requests to the Wikipedia.
I got my answer (Wikimedia Operators). Thanks.
