### ISSUE TITLE
Exception opening file 

### ISSUE THREAD

**Issue by xuangestallone** [sunnyszy/lrb#16]
![image](https://user-images.githubusercontent.com/13444302/196990630-7f71fa57-f7d6-4e3e-9e3a-00c67c2042bc.png)

**Comment by xuangestallone** [comment]
I manually install the simulator in my docker, and test it . I encountered the problem shown above. It looks like the file failed to open, What is the specific reason?

**Comment by sunnyszy** [comment]
Hi @xuangestallone , the simulator seems not able to find the trace file. Can you double check the file is correctly mounted (e.g. through debug mode)?

**Comment by xuangestallone** [comment]
Thank you very much! I found the answer to my question： The dataset path is wrong.    Sorry that I have another question, Where can I find the dataset mentioned in your paper (i.e., CDN-A, CDN-B and CDN-C)?

**Comment by sunnyszy** [comment]
Great. For the datasets, you can find the wiki one (and a newer version) here: https://github.com/sunnyszy/lrb#traces. For other CDN datasets, I'm afraid that they are not open-sourced.
