### ISSUE TITLE
Training LRB on non-CDN data 

### ISSUE THREAD

**Issue by anoopubc** [sunnyszy/lrb#24]
I want to get some information on the ML model itself and I am not sure if it's in this repo. I am looking to train it on my specific dataset unrelated to CDN. I am not quite sure if the extra_features column allows me flexibility or if there is somewhere else I should look. 

Any information would be helpful and thanks so much!

**Comment by sunnyszy** [comment]
Hi @anoopubc, the model is just standard lightgbm model, and you can find the creation: https://github.com/sunnyszy/lrb/blob/master/src/caches/lrb.cpp#L40. You can find more detailed params in the lrb.h file.
