### ISSUE TITLE
Calculate hit rate

### ISSUE THREAD

**Issue by sumuzhao** [sunnyszy/lrb#7]
Hi, thanks for open-sourcing this amazing project. In your paper you focus on the byte miss ratio, but I prefer to know the general hit rate. 

So In the simulation.h, I added two counters inside the class Framework, as uint64_t cnt = 0, hit = 0;
And in the similation.cpp, in the simulate() function, 
originally, 
        if (is_admitting) {
            bool is_hit = webcache->lookup(*req);
            if (!is_hit) {
                update_metric_req(byte_miss, obj_miss, size);
                update_metric_req(rt_byte_miss, rt_obj_miss, size)
                webcache->admit(*req);
            }
        } else {
            update_metric_req(byte_miss, obj_miss, size);
            update_metric_req(rt_byte_miss, rt_obj_miss, size)
        }
Now, 
        cnt++;   //here!!!
        if (is_admitting) {
            bool is_hit = webcache->lookup(*req);
            if (!is_hit) {
                update_metric_req(byte_miss, obj_miss, size);
                update_metric_req(rt_byte_miss, rt_obj_miss, size)
                webcache->admit(*req);
            } else {
                hit++;  //here!!!
            }
        } else {
            update_metric_req(byte_miss, obj_miss, size);
            update_metric_req(rt_byte_miss, rt_obj_miss, size)
        }

And finally I use hit / cnt to get the hit rate. Is this correct? Thanks a lot!

**Comment by sunnyszy** [comment]
Hi Sumu,

Yes, that seems good to me. I didn't see any problem with your modification. BTW you can also calculate the hit rate by existing variables obj_miss, obj_req: 
     hit rate = 1 - (obj_miss/obj_req)

Feel free to choose whichever way you free convenient.

**Comment by sumuzhao** [comment]
Thanks for your quick response.
